version: "3"
services:
  api:
    container_name: api
    image: avinty/avinty-epd-api:latest
    ports:
      - "8080:8080"
    links:
      - mongo
      - kafka
  mongo:
    container_name: mongo
    image: mongo
    # volumes:
    #   - c:/temp/data:/data/db
    ports:
      - "27017:27017"
  kafka:
    container_name: kafka
    image: avinty/avinty-epd-kafka:latest
    ports:
      - "2181:2181"
      - "9092:9092"
  # adfsso:
  #   container_name: adfsso
  #   image: avinty/avinty-epd-adfsso:latest
  agenda:
    container_name: agenda
    image: avinty/avinty-epd-agenda:latest
  main:
    container_name: main
    image: avinty/avinty-epd-main:latest
    ports:
      - "80:3000"
    links:
      - api
      # - adfsso
      - agenda
